HW7 is completed
vrnvgasu/home_work pull request #7
Opened 2024-10-20 17:55 UTC by vrnvgasu

2024-10-21 10:07 UTC, engineer-go requested changes

2024-10-21 10:07 UTC, engineer-go commented on hw07_file_copying/copy.go
>  var (
Либо удалите неиспользуемую ошибку, либо добавьте проверку что файл подходит, т.е. что мы читаем из обычного файла, а не к примеру из /dev/urandom

2024-10-21 10:07 UTC, engineer-go commented on hw07_file_copying/copy_test.go
>  }
добавьте пожалуйста тест не касающийся test.sh - он и так проверяется в CI/CD пайплайне, т.е. сейчас вы просто дублируете уже существующий функционал.

2024-10-21 18:46 UTC, vrnvgasu commented on hw07_file_copying/copy.go
>  var (
Добавил проверку

2024-10-21 18:47 UTC, vrnvgasu commented on hw07_file_copying/copy_test.go
>  }
Добавил тесты

2024-10-23 04:44 UTC, ityulkanov approved these changes

2024-10-23 06:52 UTC, merged